### ISSUE TITLE
Question: Do you have paid CloudFlare Workers, does't it cost bandwidth fee?

### ISSUE THREAD

**Issue by meteorsnows** [judge2020/cloudflare-file-hosting#3]
Question: Do you have paid CloudFlare Workers, does't it cost bandwidth fee? Afraid it count in CloudFlare CDN, then it would not make it attractive as other serverless.

**Comment by judge2020** [comment]
You can see the pricing for Workers Unlimited here https://workers.cloudflare.com/sites#plans and the pricing for this is available at https://docs.google.com/spreadsheets/d/1seiWWouWcN1vc3RCoCDy0I5-WbZmAwIZRd7K3Ju8WCY/edit?usp=sharing.
